Update Pipeline Service documentation
redhat-appstudio/book pull request #105
Opened 2023-05-30 20:01 UTC by Roming22

Add information about the new appstudio-pipeline service account.

2023-05-30 20:04 UTC, arewm requested changes
Looks good overall on a cursory glance!

2023-05-30 20:04 UTC, arewm commented on book/pipeline-service.md
> +TThe service should offer users a service account for running pipelines.
```suggestion
The service should offer users a service account for running pipelines.
```

2023-05-30 20:11 UTC, Roming22 commented on book/pipeline-service.md
> +TThe service should offer users a service account for running pipelines.
Fixed

2023-05-30 20:18 UTC, arewm approved these changes

2023-05-30 20:19 UTC, adambkaplan requested changes
Two items:

1. There should be an associated [ADR](https://github.com/redhat-appstudio/book/tree/main/ADR) with this change - we need to document why we moved away from using the out-of-box RBAC from OpenShift Pipelines and the resulting impact on AppStudio.
2. Since this repo captures technical documentation, we should aim to be more specific when it comes to the following:
   1.  What is in the `appstudio-pipelines-scc` ClusterRole (I also don't see the SCC itself documented anywhere here)
   2. What is in the `appstudio-pipelines-runner` ClusterRole (perhaps a high level description is sufficient).
   3. How CRT creates the associated ClusterRole, service account, and role bindings.

2023-05-30 20:19 UTC, adambkaplan commented on book/pipeline-service.md
> +TThe service should offer users a service account for running pipelines.
nit: spelling

```suggestion
The service should offer users a service account for running pipelines.
```

2023-05-30 22:14 UTC, Roming22 commented on book/pipeline-service.md
> +The Pipeline Service component is in charge of the `appstudio-pipelines-scc` ClusterRole, while CRT is responsible for the `appstudio-pipelines-runner` ClusteRole.
Fixed.

2023-05-30 22:15 UTC, Roming22 commented on book/pipeline-service.md
> +TThe service should offer users a service account for running pipelines.
Fixed

2023-05-30 22:20 UTC, Roming22 commented
@adambkaplan 
1. ADR added.
2. I've put a link to the definitions of the ClusterRoles. That should be enough, unless some specific permission needs additional context. As for how CRT creates the resources, I'm not sure that it would fall under the AppStudio doc. Is there specific information you had in mind?

2023-05-31 13:31 UTC, adambkaplan approved these changes
LGTM

2023-05-31 13:31 UTC, adambkaplan commented on ADR/0025-appstudio-pipeline-serviceaccount.md
> +# 2%. appstudio-pipeline Service Account
Meant to be 25?

```suggestion
# 25. appstudio-pipeline Service Account
```

2023-05-31 13:31 UTC, adambkaplan commented on ADR/0025-appstudio-pipeline-serviceaccount.md
> +The resource is defined [here](https://github.com/openshift-pipelines/pipeline-service/blob/main/operator/gitops/argocd/pipeline-service/openshift-pipelines/appstudio-pipelines-scc.yaml).
Big :+1: here!

2023-05-31 13:36 UTC, merged

2023-05-31 14:17 UTC, sbose78 commented on ADR/0025-appstudio-pipeline-serviceaccount.md
> +The resource is defined [here](https://github.com/openshift-pipelines/pipeline-service/blob/main/operator/gitops/argocd/pipeline-service/openshift-pipelines/appstudio-pipelines-scc.yaml).
👍