Add initial service page for Enterprise Contract
redhat-appstudio/book pull request #18
Opened 2022-11-04 19:56 UTC by simonbaird

Ref: https://issues.redhat.com/browse/HACBS-1374

2022-11-07 14:50 UTC, lcarva reviewed
Good progress so far!

2022-11-09 20:47 UTC, simonbaird commented on book/enterprise-contract.md
> +container image attestations, and the Enterprise Contract team members were
Agreed. The teams and responsibilities are not on topic here.

2022-11-09 20:47 UTC, simonbaird commented on book/enterprise-contract.md
> +### Enterprise Contract Renovate Bot
Done.

2022-11-09 20:47 UTC, simonbaird commented on book/enterprise-contract.md
> +- The container image has a pipeline run attestation created by Tekton Chains
Fixed.

2022-11-10 15:09 UTC, simonbaird commented on book/enterprise-contract.md
> +task bundle is created.
@lcarva I'm not sure I explained this well since I'm a little fuzzy on how it works. Lmk if you have some ideas how to describe this better.

2022-11-10 15:25 UTC, robnester-rh commented on book/enterprise-contract.md
> +[here](https://hacbs-contract.github.io/ec-policies/). In includes rules for a
Typo? Should this be `It includes`

2022-11-10 15:39 UTC, simonbaird commented on book/enterprise-contract.md
> +task bundle is created.
Could also be something to think about and iterate on later...

2022-11-10 21:06 UTC, lcarva approved these changes

2022-11-11 14:42 UTC, amfred approved these changes

2022-11-11 14:43 UTC, amfred commented
We might just need two approvals?  I added one.

2022-11-14 22:52 UTC, gorkem requested changes
I have a few small cosmetic changes only

2022-11-14 22:52 UTC, gorkem commented on book/enterprise-contract.md
> +
the link is broken

2022-11-14 22:52 UTC, gorkem commented on book/enterprise-contract.md
> +and data sources, and any other required configuration.
verifying -> verify

2022-11-14 22:52 UTC, gorkem commented on book/enterprise-contract.md
> +The reference set of policy rules created for the HACBS MVP are defined
I suppose this is going to be the location for default/reference policies not only for MVP and afterwards too. Let's remove the qualifier "HACBS MVP" only.

2022-11-14 22:52 UTC, gorkem commented on book/enterprise-contract.md
> +HACBS users can leverage the Renovate Bot service to keep such Tekton bundle
Link to Renovate

2022-11-15 01:02 UTC, simonbaird commented
Thanks very much for the thoughtful review @gorkem. Addressed your comments in [this revision](https://github.com/redhat-appstudio/book/compare/bf1fd6551a2dd52109f3bed9e41591036db06242..403be2650891b4e5e57ab8fd560cfa0ab4c7eed3).

2022-11-15 01:05 UTC, simonbaird commented
In f3b5dc1I just capitalized "Conftest" in two places.

2022-11-15 11:54 UTC, gorkem approved these changes
Thanks

2022-11-15 19:58 UTC, simonbaird commented
Safe to merge?

2022-11-15 21:24 UTC, merged